### ISSUE TITLE
Issue with OpenUPM .UnityPackage on Windows

### ISSUE THREAD

**Issue by username-for-github** [ViRGIS-Team/gdal-upm#5] opened 2021-07-17 01:00 UTC
Hello! I encountered an issue I believe you should be aware of on Windows 10.  I attempted to install the 3.3.1 .UnityPackage from https://openupm.com/packages/com.virgis.gdal/  ---- everything seemed to work fine at first, then after the scoped registry was updated Unity threw an error that a file could not be found, and ultimately asked to be force quit.  Upon the crash the many project folders were missing and had been permanently erased.  I was able to recreate this in a new project on Unity 2020.3.3f1 and Unity 2021.1.11f1.  I was unable to recreate the issue on Mac OS 11.4.

I've also opened a bug report with Unity.  

Thanks for taking a look!

**Comment by runette** [comment] 2021-07-22 09:55
Thank you for your feedback and interest in the package and sorry for the problems this must have caused you.

This is caused by the following known bug : https://github.com/ViRGIS-Team/CondaExtensions/issues/1

Unfortunately, this issues was only raised on the source repo. It is actually only present on Windows and is caused by one of the Conda commands on Windows not actually doing what the spec says it should. This means that what you describe can happen if there is no folder called `Conda` in the `Assets` folder.

I must admit that having found the bug - I intended to fix it by moving from Conda to Mamba. However, we have not found the time to make that change - so I need to go in and do a quick fix. I will do that today and update the UPM packages.

**Comment by runette** [comment] 2021-07-22 23:03
Should be fixed in release 3.3.2

**Comment by runette** [comment] 2021-07-23 08:29
Correction - there is still a problem if there is a space in the Unity Project name but it does not delete anything now. The "space in name " bug is proving very hard to diagnose

**Comment by runette** [comment] 2021-07-28 12:30
complete fix in release 3.3.100

**Closed by runette** 2021-07-28 12:30 UTC
